import "../styles/global.css";

import { Metadata } from "next";
import Navigations from "../components/Navigations";

export const metadata: Metadata = {
  title: {
    template: "%s | Next Movie",
    default: "Next Movie",
  },
  description: "Generated by Next.js",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <main>
          <Navigations />
          {children}
        </main>
      </body>
    </html>
  );
}
